### ISSUE TITLE
Some smaller layout-things

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-orte#6]
- [x] also bei reisen netzwerk auf einer karte wird erst was angezeigt, wenn man haken setzt auf "network example" – lässt sich das automatisch einstellen, damit man am anfang was sieht?
- [x] das würde ich schmeißen: https://arthur-schnitzler.github.io/schnitzler-orte/towers.html weil irgendwie sehe ich nicht viel
- [x] #8
- [x] arcs: wieso ist das letzte jahr beim filter 1938, das sollte 1931 sein

**Comment by csae8092** [comment]
closing issue
